project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sung Manhin"
  site-url: https://sungmanhin.github.io
  favicon: misc/logo.png
  repo-url: https://github.com/sungmanhin/sungmanhin.github.io
  repo-actions: [edit, issue]

  page-footer:
    left: "&copy; Copyright 2024, Sung Manhin"
    right: 
      - icon: github
        href: https://github.com/sungmanhin/sungmanhin.github.io
  navbar:
    background: "#b5d9f0"
    search: true
    right:

      - text: "Publications"
        icon: file-earmark-text
        href: publications/index.qmd

      - text: "Talks"
        icon: chat-right-text
        href: talks/index.qmd

      - text: "Blog"
        icon: pen
        href: blog/index.qmd

      - text: "About me"
        icon: person-circle
        href: about.qmd



format:
  html:
    css: styles.scss


